theme: jekyll-theme-minimal
logo: /assets/img/521D2AD1-978F-45A6-A9D0-580A63B52990.png
title: HCR2 REFERENCE
description: <center> <a href=".\"><img src="https://cdn.discordapp.com/attachments/806343355264401478/848994894865104896/cooltext385495335534000.png" alt="INFO"></a></center>
google_analytics: G-SFJ80L12D6
linezero: <a href=".\"><img src="https://media.discordapp.net/attachments/806343355264401478/848994894865104896/cooltext385495335534000.png?width=125&height=110" alt=""></a>
lineone: <a href="http://fw.hcr2.info">Friendly Wars</a> - <a href="http://tw.hcr2.info">Tractor Wars</a> - <a href="http://vehicles.hcr2.info">Vehicles</a>
linetwo: <a href="./blog.html">Log</a> - <a href="./tips.html">Tips</a> - <a href="./chests.html">Chests</a> - <a href="./memes.html">Memes</a> - <a href="./gm.html">GM</a> - <a href="./faq.html">FAQ</a>
buttonone:  <a href=".\#best-distance-parts-by-vehicle" class="btn"><strong>Adventure Parts</strong></a> 
buttontwo: <a href=".\#tracks-by-map-type-and-distance" class="btn"><strong>Cup Tracks</strong></a> 
buttonthree: <a href=".\#daily-checklist" class="btn"><strong>Daily Checklist</strong></a>           
footerone:  <a href="#top"><img src="https://cdn.discordapp.com/attachments/806343355264401478/820076457690398751/GBG-team-logo-125.png" alt="Gas Brake Go"/></a>
footertwo:  <a href="mailto:dadahcr2@gmail.com">dadahcr2@gmail.com</a> ~ dada#1710
